### ISSUE TITLE
Upgrading to Nuxt V4

### ISSUE THREAD

**Issue by yosefeliezrie** [vernaillen/wpnuxt-module#74]
Given that Nuxt v4 will likely be shipping on June 14 2024 (see here https://nuxt.com/blog/looking-forward-2024). This is an initial issue to discover what is to upgrade this plugin to Nuxt v4]

Also we should get this updated as well https://github.com/nuxt/modules/blob/main/modules/wp-nuxt.yml see #76

**Comment by vernaillen** [comment]
There is now an Upgrade Guide on the Nuxt website migration guide: https://nuxt.com/docs/getting-started/upgrade

I created this branch to start testing the module in Nuxt v4 compatibility mode: https://github.com/vernaillen/wpnuxt-module/tree/74-upgrading-to-nuxt-v4

**Comment by vernaillen** [comment]
> Also we should get this updated as well https://github.com/nuxt/modules/blob/main/modules/wp-nuxt.yml see #76

That's a good idea, but first I think new WPNuxt module should be stable and there's still some work on the documentation.

**Comment by yosefeliezrie** [comment]
@vernaillen thanks for doing this.  I'll begin testing next week. I'm located in Australia. Perhaps we could set up a time to chat. I would like to collaborate with you on this.
